kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: keda-demo
nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      - containerPort: 80 
        hostPort: 8000
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 443 
        hostPort: 8443
        listenAddress: "127.0.0.1"
        protocol: TCP
