kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: app
spec:
    hosts:
    - localhost
    pathPrefixes:
    - /
    scaleTargetRef:
        name: app
        kind: Deployment
        apiVersion: apps/v1
        service: app
        port: 8000
    replicas:
        min: 0
        max: 10
    scaledownPeriod: 120
    scalingMetric: # requestRate and concurrency are mutually exclusive
        requestRate:
            granularity: 1s
            targetValue: 10
            window: 1m
        # concurrency:
        #     targetValue: 10
